<b> This notebook is a compilation of simple samples around the gears of Machine Learning and Deep Learning operations, nothing else that algebra operations using matrix or tensor operations, with Numpy, Pytorch and Keras / Tensorflow in order to show the similarities and differences around them.

In [1]:
import numpy as np
import torch
import tensorflow as tf

## Numpy

In [22]:
## Basics

# Scalars (Rank 0 tensors)
x = np.array(5)
print(f'The number of dimensions of a scalar is {x.ndim}')

# Vectors (Rank 1 tensors) --> (samples) in a column
y = np.array(([1,2,3,4]))
print(f'The number of dimensions of a vector is {y.ndim}')

# Matrices (Rank 2 Tensors) --> Tabular data (samples, features)
      
z = np.array([[1,2,4],
             [9, 13, 14],
             [98, 52, 72]])
print(f'The number of dimensions of a matrix is {z.ndim}')

# Higher Rank tensors, 3 and above
# Time Series --> Rank 3 tensors (samples, timesteps, features)
# Images --> Rank 4 tensors (samples, weight, height, channels)
# Video --> Rank 5 ((samples, frames, height, width, channels))
      
alpha = np.array(
    [
        [
            [5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2]],
        [
            [5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2]],
        [
            [5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2]
        ]
    ]
)
print(f'The number of dimensions of a tensor is {alpha.ndim}')

The number of dimensions of a scalar is 0
The number of dimensions of a vector is 1
The number of dimensions of a matrix is 2
The number of dimensions of a tensor is 3


## Tensorflow / Keras and Pytorch

In [31]:
x1 = np.ones((2,1))
print(f'Vector of ones in Numpy {x1}')

x1_tf = tf.ones((2,1))
print(f'Vector of ones in Tensorflow {x1_tf}')

x1_pytorch = torch.ones((2,1))
print(f'Vector of ones in Pytorch {x1}')

x_zeros = np.zeros((2,1))
print('Array of zeros in Numpy')
print(x_zeros)
print()
x_zeros_tf = tf.zeros((3,1))
print('Array of zeros in Tensorflow')
print(x_zeros_tf)
print()
x_zeros_pytorch = torch.zeros((3,1))
print('Array of zeros in Pytorch')
print(x_zeros_pytorch)
print()

Vector of ones in Numpy [[1.]
 [1.]]
Vector of ones in Tensorflow [[1.]
 [1.]]
Vector of ones in Pytorch [[1.]
 [1.]]
Array of zeros in Numpy
[[0.]
 [0.]]

Array of zeros in Tensorflow
tf.Tensor(
[[0.]
 [0.]
 [0.]], shape=(3, 1), dtype=float32)

Array of zeros in Pytorch
tensor([[0.],
        [0.],
        [0.]])



In [32]:
# Creating tensor from from list and from Numpy

a = [1,2,3]
b = np.array([3.0,6.0,8.0,4.0])

tensor_tf = tf.convert_to_tensor(b)
print("Converted numpy array into tensor in Tensorflow:")
print(tensor_tf)
print()
t_b = torch.from_numpy(b)
print("Converted numpy array into tensor in Tensorflow:")
print(t_b)


Converted numpy array into tensor in Tensorflow:
tf.Tensor([3. 6. 8. 4.], shape=(4,), dtype=float64)

Converted numpy array into tensor in Tensorflow:
tensor([3., 6., 8., 4.], dtype=torch.float64)


In [36]:

x = np.arange(12)
print(x)
print()

x_torch = torch.arange(12, dtype=torch.float32)
print(x_torch)
print()
x_tf = tf.range(12, dtype=tf.float32)
print(x_tf)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.], shape=(12,), dtype=float32)



In [37]:
# To get the shape all use same command
print(x_torch.shape)
print(x_tf.shape)

torch.Size([12])
(12,)


In [40]:
# Number of elements
print(x_torch.numel())
print(tf.size(x_tf))

12
tf.Tensor(12, shape=(), dtype=int32)


In [42]:
# Reshaping operation

X_torch_reshaped = x_torch.reshape(3, 4)
print(X_torch_reshaped)

X_tf_reshape = tf.reshape(x_tf, (3, 4))
print(X_tf_reshape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


In [46]:
# Random Distributions normal, uniform

torch_normal = torch.randn(3, 4)
print(torch_normal)
print()
tf_normal = tf.random.normal(shape=(3, 4), mean = 0, stddev = 1)
print(tf_normal)

tensor([[ 0.0277,  1.5940,  0.0547,  0.9075],
        [-0.0830, -0.7713,  0.2638, -0.4091],
        [ 0.3752,  0.7395,  0.9938, -1.4249]])

tf.Tensor(
[[-0.6559008  -0.7705256   0.64018154 -1.7344484 ]
 [ 0.01427678 -0.566826    0.09488212 -2.305249  ]
 [ 1.2057362   1.2659192   0.8795296   1.6820922 ]], shape=(3, 4), dtype=float32)


In [50]:
torch_uniform = torch.rand(3,4)
print(torch_uniform)
print()
tf_unif = tf.random.uniform([3,4], minval = 0., maxval = 1.)
print(tf_unif)

tensor([[0.2805, 0.2310, 0.7696, 0.9047],
        [0.3666, 0.7605, 0.1266, 0.0117],
        [0.1890, 0.5101, 0.8271, 0.3158]])

tf.Tensor(
[[0.13370037 0.24581933 0.5363015  0.454782  ]
 [0.8107952  0.7274295  0.51091313 0.36327183]
 [0.83478    0.67665136 0.57968926 0.16813481]], shape=(3, 4), dtype=float32)


In [ ]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [51]:
# In Pytorch tensors can be modified
X_torch = X_torch_reshaped
print(X_torch_reshaped)
X_torch[1,2] = 3
X_torch

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  3.,  7.],
        [ 8.,  9., 10., 11.]])

In [55]:
# In Tensorflow tensors are not assignable, they have to be converted to .Variable,
# the state of a variable can be changed with the assign function

print(X_tf_reshape)

X_var_tf = tf.Variable(X_tf_reshape)
X_var_tf[1, 2].assign(3)
X_var_tf

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  3.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [64]:
# Remove unnecesary dimensions
torch_squeze = torch.squeeze(X_torch, 0)
print(torch_squeze.shape)
print(X_torch.shape)

torch.Size([3, 4])
torch.Size([3, 4])


## Math operations

In [65]:
# https://pytorch.org/docs/stable/torch.html#math-operations
# Exponential
print(torch.exp(X_torch))
print(tf.exp(X_var_tf))

# Others
# Pytorch
# torch.mean(),torch.std(), torch.matmul(),torch.sum(),torch.zeros_like(Y)

# Tensorflow
# tf.mean(),tf.std(), tf.matmul(a,b),tf.reduce_sum(X),tf.Variable(tf.zeros_like(Y))

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 2.0086e+01, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])
tf.Tensor(
[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 2.0085537e+01 1.0966332e+03]
 [2.9809580e+03 8.1030835e+03 2.2026465e+04 5.9874141e+04]], shape=(3, 4), dtype=float32)


In [67]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y, x - y, x * y, x / y, x ** y)
print()
x_tf = tf.constant([1.0, 2, 4, 8])
y_tf = tf.constant([2.0, 2, 2, 2])
print(x_tf + y_tf, x_tf - y_tf, x_tf * y_tf, x_tf / y_tf, x_tf ** y_tf)

tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])

tf.Tensor([ 3.  4.  6. 10.], shape=(4,), dtype=float32) tf.Tensor([-1.  0.  2.  6.], shape=(4,), dtype=float32) tf.Tensor([ 2.  4.  8. 16.], shape=(4,), dtype=float32) tf.Tensor([0.5 1.  2.  4. ], shape=(4,), dtype=float32) tf.Tensor([ 1.  4. 16. 64.], shape=(4,), dtype=float32)


## Split, Stack, Concatenate Tensors

In [68]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [71]:
torch.stack([X,Y], axis = 0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]])

In [72]:
torch.stack([X,Y], axis = 1)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 2.,  1.,  4.,  3.]],

        [[ 4.,  5.,  6.,  7.],
         [ 1.,  2.,  3.,  4.]],

        [[ 8.,  9., 10., 11.],
         [ 4.,  3.,  2.,  1.]]])

In [69]:
torch_splits = torch.chunk(X, 2)
print(torch_splits)

(tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), tensor([[ 8.,  9., 10., 11.]]))


In [73]:
# In Tensorflow
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

In [74]:
x = tf.linalg.matmul([[1]], [[2, 3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [77]:
x_matmul_torch= torch.matmul( torch.arange(12, dtype=torch.float32).reshape((3,4)),
                              torch.arange(12, dtype=torch.float32).reshape((4,3)))
print(x_matmul_torch)

tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])
